### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by jarry9** [Bradan/Gnome-On-Screen-Keyboard-Button#3]
Hi,

I am using:

Ubuntu Gnome 16.04 LTS 64 Bit Eng. The system is fully updated. This extension not working on me. I re-install it but nothin changed :/

Thank you

**Comment by Bradan** [comment]
What is your gnome-shell version? What exactly does not work for you? Does it show the icon on the top right of the screen? Did you enable the accessibility setting? If not, your first click on the button/icon enables it, but it doesn't open the keyboard, yet.

**Comment by ekg** [comment]
This also does not work for me. After one click I get the accessibility menu but no on screen keyboard. I'm on Ubuntu 18.04 and using the current default version of Gnome shell. The same effect happens whether I'm on wayland or vanilla x11 gnome shell.

**Comment by Bradan** [comment]
This happens on every tap on the button or just on the first? Does Ubuntu have a original Gnome version or a modified one with a different default on screen keyboard?

**Comment by ekg** [comment]
I've just learned that you can swipe up from the bottom of the screen to make the keyboard appear in 18.04. This solves the problem for me, but unfortunately it makes your button extension obsolete.

**Comment by Bradan** [comment]
Ok I haven't updated my laptop for a while (about half a year) and now that I did, I'm seeing you're right. However this seems to be completely different to the original post of the issue, since I had no problems when this issue was opened. However, you already mentioned that the swipe up finally works. Still, I would not call this extension obsolete, since some users might prefer a tap instead of a swipe to open up the keyboard.

**Comment by sophieneuenmuller** [comment]
Swipes work in Wayland, but if you are on XOrg you are out of luck, which the button covers. And no, it doesn't work for me either. Completely fresh Ubuntu 18.04 install, and it doesn't work. It does activate accessibility on the first touch, but it doesn't show when tapping it. Maybe it was Gnome 3.28 new OSK changes?

**Comment by Bradan** [comment]
I kind of solved the issue at least for X11. Maybe it also works with wayland, but I still have problems with it. The keyboard however will always appear on the first monitor. And remember: the first click on the button will only enable the accessibility setting, if it wasn't enabled before.
